---
kind: pipeline
type: docker
name: default

steps:
  - name: create release
    image: docker.io/kameshsampath/drone-github-release-please:v0.0.2
    pull: if-not-exists
    settings:
      github_token:
        from_secret: github_token
      extra_options: |
        release-type: simple
        bump-patch-for-minor-pre-major: true
    when:
      event:
        - push

trigger:
  branch:
    - main
---
kind: pipeline
type: docker
name: release-artifacts

steps:
  # need to fetch the tags to be available in next steps
  - name: fetch
    image: alpine/git
    commands:
    - git fetch --tags
  
  - name: release-binaries
    image: goreleaser/goreleaser
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - goreleaser release

  - name: release-image
    image: gcr.io/kaniko-project/executor:debug
    pull: if-not-present
    commands:
      - mkdir -p "/kaniko/.docker"
      - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "$IMAGE_REGISTRY_USER" "$IMAGE_REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > "/kaniko/.docker/config.json"
      - >
        /kaniko/executor 
        --build-arg "DRONE_TAG=$DRONE_TAG"
        --context .
        --dockerfile docker/Dockerfile
        --destination "$IMAGE_REGISTRY/$DESTINATION_IMAGE:$DRONE_TAG"
        --customPlatform=linux/arm64
        --customPlatform=linux/amd64
        --use-new-run
        --verbosity=debug
    environment:
      DESTINATION_IMAGE:
        from_secret: destination_image
      IMAGE_REGISTRY:
        from_secret: image_registry
      IMAGE_REGISTRY_USER:
        from_secret: image_registry_username
      IMAGE_REGISTRY_PASSWORD:
        from_secret: image_registry_password

trigger:
  event:
    - tag
