---
kind: pipeline
type: docker
name: default

# remove this section if your CPU is amd64
platform:
  os: linux
  arch: amd64

steps:
  - name: hello
    image: busybox
    commands:
      - echo "Hello world ${DRONE_TAG}"
    when:
      event:
        - tag

  - name: create release
    image: docker.io/kameshsampath/drone-github-release-please:v0.0.2
    pull: if-not-exists
    settings:
      github_token:
        from_secret: github_token
      extra_options: |
        release-type: simple
        bump-patch-for-minor-pre-major: true
    when:
      event:
        - push
trigger:
  branch:
    - main
