---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: hello
    image: busybox
    commands:
      - echo "Hello world ${DRONE_TAG}"
    when:
      event:
        - tag

  - name: release-image
    image: docker.io/docker:20.10.17-alpine3.16
    pull: if-not-present
    commands:
      - 'docker login -u "$IMAGE_REGISTRY_USER" -p "$IMAGE_REGISTRY_PASSWORD"'
      - "docker buildx inspect $BUILDER || docker buildx create --name=$BUILDER --driver=docker-container --driver-opt=network=host"
      - "docker pull $DESTINATION_IMAGE:$DRONE_TAG && echo 'Failure: Tag already exists' || docker buildx build --push --builder=$BUILDER --platform=linux/amd64,linux/arm64 --build-arg TAG=$DRONE_TAG --tag=$DESTINATION_IMAGE:$DRONE_TAG ."
    environment:
      BUILDER: buildx-multi-arch
      DESTINATION_IMAGE:
        from_secret: destination_image
      IMAGE_REGISTRY:
        from_secret: image_registry
      IMAGE_REGISTRY_USER:
        from_secret: image_registry_username
      IMAGE_REGISTRY_PASSWORD:
        from_secret: image_registry_password
    when:
      event:
        - tag

  - name: create release
    image: docker.io/kameshsampath/drone-github-release-please:v0.0.2
    pull: if-not-exists
    settings:
      github_token:
        from_secret: github_token
      extra_options: |
        release-type: simple
        bump-patch-for-minor-pre-major: true
    when:
      event:
        - push
trigger:
  branch:
    - main
