---
kind: pipeline
type: docker
name: "Create Release"

trigger:
  branch:
    - main

steps:
  - name: release-please
    image: docker.io/kameshsampath/drone-github-release-please:v0.0.2
    pull: if-not-exists
    settings:
      github_token:
        from_secret: github_token
      extra_options: |
        release-type: simple
        bump-patch-for-minor-pre-major: true
    when:
      event:
        - push
---
kind: pipeline
type: docker
name: "Release Binaries"

trigger:
  event:
    - tag

steps:
  # need to fetch the tags to be available in next steps
  - name: fetch
    image: alpine/git
    commands:
    - git fetch --tags
  
  - name: goreleaser
    image: goreleaser/goreleaser
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - goreleaser release
---
kind: pipeline
type: docker
name: "Release Docker Image(amd64)"

depends_on:
 - "Release Binaries"

trigger:
  event:
    - tag

platform:
  os: linux
  arch: amd64

steps:
  - name: release-image
    image: gcr.io/kaniko-project/executor:debug
    pull: if-not-present
    commands:
      - mkdir -p "/kaniko/.docker"
      - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "$IMAGE_REGISTRY_USER" "$IMAGE_REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > "/kaniko/.docker/config.json"
      - >
        /kaniko/executor 
        --build-arg "GIT_TAG=${DRONE_TAG:1}"
        --build-arg "TARGETARCH=${DRONE_STAGE_ARCH}"
        --context .
        --dockerfile docker/Dockerfile
        --destination "$IMAGE_REGISTRY/$DESTINATION_IMAGE:$DRONE_TAG"
        --customPlatform="linux/${DRONE_STAGE_ARCH}"
        --use-new-run
        --verbosity=debug
    environment:
      DESTINATION_IMAGE:
        from_secret: destination_image
      IMAGE_REGISTRY:
        from_secret: image_registry
      IMAGE_REGISTRY_USER:
        from_secret: image_registry_username
      IMAGE_REGISTRY_PASSWORD:
        from_secret: image_registry_password
---
kind: pipeline
type: docker
name: "Release Docker Image(arm64)"

depends_on:
 - "Release Binaries"

trigger:
  event:
    - tag

platform:
  os: linux
  arch: arm64

steps:
  - name: release-image
    image: gcr.io/kaniko-project/executor:debug
    pull: if-not-present
    commands:
      - mkdir -p "/kaniko/.docker"
      - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "$IMAGE_REGISTRY_USER" "$IMAGE_REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > "/kaniko/.docker/config.json"
      - >
        /kaniko/executor 
        --build-arg "GIT_TAG=${DRONE_TAG:1}"
        --build-arg "TARGETARCH=${DRONE_STAGE_ARCH}"
        --context .
        --dockerfile docker/Dockerfile
        --destination "$IMAGE_REGISTRY/$DESTINATION_IMAGE:$DRONE_TAG"
        --customPlatform="linux/${DRONE_STAGE_ARCH}"
        --use-new-run
        --verbosity=debug
    environment:
      DESTINATION_IMAGE:
        from_secret: destination_image
      IMAGE_REGISTRY:
        from_secret: image_registry
      IMAGE_REGISTRY_USER:
        from_secret: image_registry_username
      IMAGE_REGISTRY_PASSWORD:
        from_secret: image_registry_password
