---
kind: pipeline
type: docker
name: default

# remove this section if your CPU is amd64
platform:
  os: linux
  arch: arm64

steps:
  - name: hello
    image: busybox
    commands:
      - echo hello world

  - name: release please
    image: docker.io/kameshsampath/drone-release-please
    pull: never
    settings:
      token:
        from_secret: github_token
      extra_options: >-
        --release-type=simple
        --bump-patch-for-minor-pre-major=true

trigger:
  branch:
    - main
